// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUeOM-04Kj0f7zUzOmB-kmA5dXjTFD3VY',
    appId: '1:164775569652:web:1360ae412eb8e5b40d56a1',
    messagingSenderId: '164775569652',
    projectId: 'maahey-9acaf',
    authDomain: 'maahey-9acaf.firebaseapp.com',
    storageBucket: 'maahey-9acaf.appspot.com',
    measurementId: 'G-EN5TF578FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8x75KeSDTsIsUzu-QlXRhZ6OCwlaJG1Q',
    appId: '1:164775569652:android:75091be78b99126e0d56a1',
    messagingSenderId: '164775569652',
    projectId: 'maahey-9acaf',
    storageBucket: 'maahey-9acaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9Ea13bzgqKQXvMCm2-d0qztV5QhEM44',
    appId: '1:164775569652:ios:0e538d0d087c0ee30d56a1',
    messagingSenderId: '164775569652',
    projectId: 'maahey-9acaf',
    storageBucket: 'maahey-9acaf.appspot.com',
    iosClientId: '164775569652-gicuoof6qfq8479lpffktdanng60alug.apps.googleusercontent.com',
    iosBundleId: 'com.example.maaheyFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9Ea13bzgqKQXvMCm2-d0qztV5QhEM44',
    appId: '1:164775569652:ios:0e538d0d087c0ee30d56a1',
    messagingSenderId: '164775569652',
    projectId: 'maahey-9acaf',
    storageBucket: 'maahey-9acaf.appspot.com',
    iosClientId: '164775569652-gicuoof6qfq8479lpffktdanng60alug.apps.googleusercontent.com',
    iosBundleId: 'com.example.maaheyFlutterTask',
  );
}
